[project]
name = "huorong-virdb-changelog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pefile>=2024.8.26",
    "requests>=2.32.5",
]
